game_gui_splash_palette_primary:
	.DB VDP_PALETTE_BLUE
	.DB VDP_PALETTE_WHITE
	.DB VDP_PALETTE_VIOLET_1
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_HOT_PINK
	.DB VDP_PALETTE_LIGHT_PINK
	.DB VDP_PALETTE_YELLOW
	.DB VDP_PALETTE_VIOLET_2
	; Rest is "don't care"
