game_gui_splash_palette_secondary:
	.DB VDP_PALETTE_BLUE		;3b10
	.DB VDP_PALETTE_BLACK		;3b11
	.DB VDP_PALETTE_BLACK		;3b12
	.DB VDP_PALETTE_BLACK		;3b13
	.DB VDP_PALETTE_BLACK		;3b14
	.DB VDP_PALETTE_BLACK		;3b15
	.DB VDP_PALETTE_BLACK		;3b16
	.DB VDP_PALETTE_BLACK		;3b17
	.DB VDP_PALETTE_BLACK		;3b18
	.DB VDP_PALETTE_RED		;3b19
	.DB VDP_PALETTE_BLACK		;3b1a
	; Rest is "don't care"
