game_gui_splash_palette_secondary:
	.DB VDP_PALETTE_BLUE
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_RED
	.DB VDP_PALETTE_BLACK
	; Rest is "don't care"
