game_gui_splash_palette_primary:
	.DB VDP_PALETTE_BLUE		;3b08
	.DB VDP_PALETTE_WHITE		;3b09
	.DB VDP_PALETTE_VIOLET_1		;3b0a
	.DB VDP_PALETTE_BLACK		;3b0b
	.DB VDP_PALETTE_HOT_PINK		;3b0c
	.DB VDP_PALETTE_LIGHT_PINK		;3b0d
	.DB VDP_PALETTE_YELLOW		;3b0e
	.DB VDP_PALETTE_VIOLET_2		;3b0f
	; Rest is "don't care"
