sub_game_entity_y_ordering:
	xor a
	ld (state.sort_outer_idx),a
	inc a
	ld (state.sort_inner_idx),a
@loop_outer:
	ld a,(state.sort_outer_idx)
	ld e,a
	ld d,000h
	ld hl,state.z_order_array
	add hl,de
	ld a,(hl)
	add a,a
	ld e,a
	ld hl,entities_y_pos_cache
	add hl,de
	ld e,(hl)
	inc hl
	ld d,(hl)
	ex de,hl
	ld c,(hl)
@loop_inner:
	ld a,(state.sort_inner_idx)
	ld e,a
	ld d,000h
	ld hl,state.z_order_array
	add hl,de
	ld a,(hl)
	add a,a
	ld e,a
	ld hl,entities_y_pos_cache
	add hl,de
	ld e,(hl)
	inc hl
	ld d,(hl)
	ld a,(de)
	cp c
	jr c,@no_swap
	ld c,a
	ld a,(state.sort_outer_idx)
	ld e,a
	ld d,000h
	ld hl,state.z_order_array
	add hl,de
	ld b,(hl)
	push hl
	ld a,(state.sort_inner_idx)
	ld e,a
	ld hl,state.z_order_array
	add hl,de
	ld a,(hl)
	pop de
	ld (de),a
	ld (hl),b
@no_swap:
	ld a,(state.sort_inner_idx)
	inc a
	ld (state.sort_inner_idx),a
	cp 006h
	jr nz,@loop_inner
	ld a,(state.sort_outer_idx)
	inc a
	ld (state.sort_outer_idx),a
	cp 005h
	ret z
	inc a
	ld (state.sort_inner_idx),a
	jr @loop_outer

entities_y_pos_cache:
	.DW entities.player.1.bottom.y_pos_cache
	.DW entities.player.1.top.y_pos_cache
	.DW entities.player.2.bottom.y_pos_cache
	.DW entities.player.2.top.y_pos_cache
	.DW entities.ball.y_pos_cache
	.DW entities.ball_shadow.y_pos_cache
