data_animation_attributes:
	.DW data_animation_frame_1
	.DW data_animation_frame_2
	.DW data_animation_frame_3
	.DW data_animation_frame_6
	.DW data_animation_frame_8
	.DW data_animation_frame_10
	.DW data_animation_frame_12
	.DW data_animation_frame_13
	.DW data_animation_frame_14
	.DW data_animation_frame_15
	.DW data_animation_frame_16
	.DW data_animation_frame_19
	.DW data_animation_frame_21
	.DW data_animation_frame_22
	.DW data_animation_frame_23
	.DW data_animation_frame_26
	.DW data_animation_frame_28
	.DW data_animation_frame_30
	.DW data_animation_frame_32
	.DW data_animation_frame_33
	.DW data_animation_frame_34
	.DW data_animation_frame_35
	.DW data_animation_frame_36
	.DW data_animation_frame_39
	.DW data_animation_frame_40
	.DW data_animation_frame_41
	.DW data_animation_frame_42
	.DW data_animation_frame_47
	.DW data_animation_frame_48
	.DW data_animation_frame_50
	.DW data_animation_frame_51
	.DW data_animation_frame_52
	.DW data_animation_frame_53
	.DW data_animation_frame_50
	.DW data_animation_frame_56
	.DW data_animation_frame_57
	.DW data_animation_frame_0
	.DW data_animation_frame_4
	.DW data_animation_frame_5
	.DW data_animation_frame_7
	.DW data_animation_frame_9
	.DW data_animation_frame_11
	.DW data_animation_frame_12
	.DW data_animation_frame_13
	.DW data_animation_frame_14
	.DW data_animation_frame_11
	.DW data_animation_frame_17
	.DW data_animation_frame_18
	.DW data_animation_frame_20
	.DW data_animation_frame_24
	.DW data_animation_frame_25
	.DW data_animation_frame_27
	.DW data_animation_frame_29
	.DW data_animation_frame_31
	.DW data_animation_frame_32
	.DW data_animation_frame_33
	.DW data_animation_frame_34
	.DW data_animation_frame_31
	.DW data_animation_frame_37
	.DW data_animation_frame_38
	.DW data_animation_frame_40
	.DW data_animation_frame_43
	.DW data_animation_frame_44
	.DW data_animation_frame_45
	.DW data_animation_frame_46
	.DW data_animation_frame_49
	.DW data_animation_frame_51
	.DW data_animation_frame_52
	.DW data_animation_frame_53
	.DW data_animation_frame_54
	.DW data_animation_frame_55
	.DW data_animation_frame_58
