.equ VDP_PATTERN_ADDRESS_BASE			$0000
.equ VDP_COLOR_ADDRESS_BASE				$2000
.equ VDP_NAME_TABLE_ADDRESS_BASE		$3800
.equ VDP_SPRITE_ATTRIBUTE_ADDRESS_BASE	$3f00

.equ VDP_NAME_TABLE_ROWS 28
.equ VDP_NAME_TABLE_ROWS_VISIBLE 24
.equ VDP_NAME_TABLE_COLUMNS 32

.equ VDP_TILE_SIZE 8

.equ VDP_SPRITES 32

.FUNCTION VDP_NAME_TABLE_ADDRESS(x, y) (VDP_NAME_TABLE_ADDRESS_BASE + ((y * VDP_NAME_TABLE_COLUMNS + x) * 2))
