.equ VDP_NAME_TABLE_ADDRESS_BASE $3800

.equ VDP_NAME_TABLE_COLUMNS 32
.equ VDP_NAME_TABLE_ROWS 28

.FUNCTION VDP_NAME_TABLE_ADDRESS(x, y) (VDP_NAME_TABLE_ADDRESS_BASE + ((y * VDP_NAME_TABLE_COLUMNS + x) * 2))
