gui_text_splash:
	.DB 3

	.DW VDP_NAME_TABLE_ADDRESS(4, 15)
	.DW 48
	.STRINGMAP ascii, "PUSH 1 PLAY START BUTTON"

	.DW VDP_NAME_TABLE_ADDRESS(15, 17)
	.DW 4
	.STRINGMAP ascii, "OR"

	.DW VDP_NAME_TABLE_ADDRESS(4, 19)
	.DW 48
	.STRINGMAP ascii, "PUSH 2 PLAY START BUTTON"
