gui_text_win_special:
	.DB 3

	.DW VDP_NAME_TABLE_ADDRESS(12, 3)
	.DW 14
	.STRINGMAP ascii, "YOU WIN"

	.DW VDP_NAME_TABLE_ADDRESS(6, 5)		; 372d
	.DW 30
	.STRINGMAP ascii, "CONGRATULATIONS"

	.DW VDP_NAME_TABLE_ADDRESS(9, 6)		; 374f
	.DW 36
	.STRINGMAP ascii, "YOU ARE WONDERFUL."
