sub_get_joy_p2:
	ld a,(state.joy_not_mark3)
	and a
	jr z,+
	   in a,(I_JOYPAD_1)
	   ld c,a
	   in a,(I_JOYPAD_2)
	   rl c
	   rla
	   rl c
	   rla
	   cpl
	   and JOY_MASK_ALL
	   ret
	+:

	JOY_READ_ROW JOY_ROW_JOY_SELECT, I_JOYPAD_1
	ld c,a
	in a,(I_JOYPAD_2)
	rl c
	rla
	rl c
	rla
	ld c,a

	JOY_READ_ROW JOY_P2_LEFT_ROW, I_JOYPAD_1
	JOY_CHECK_KEY JOY_P2_LEFT_BIT, JOY_BIT_LEFT
	JOY_CHECK_KEY JOY_P2_DOWN_BIT, JOY_BIT_DOWN

	JOY_READ_ROW JOY_P2_UP_ROW, I_JOYPAD_1
	JOY_CHECK_KEY JOY_P2_UP_BIT, JOY_BIT_UP

	JOY_READ_ROW JOY_P2_RIGHT_ROW, I_JOYPAD_1
	JOY_CHECK_KEY JOY_P2_RIGHT_BIT, JOY_BIT_RIGHT

	JOY_READ_ROW JOY_P2_B2_ROW, I_JOYPAD_2
	JOY_CHECK_KEY JOY_P2_B2_BIT, JOY_BIT_B2

	JOY_READ_ROW JOY_P2_B1_ROW, I_JOYPAD_2
	JOY_CHECK_KEY JOY_P2_B1_BIT, JOY_BIT_B1

	ld a,c
	cpl
	and JOY_MASK_ALL
	ret
