graphics_palette_unused:
	.DB VDP_PALETTE_BLUE
	.DB VDP_PALETTE_YELLOW
	.DB VDP_PALETTE_ORANGE_RED
	.DB VDP_PALETTE_DARK_RED
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_BLACK
	.DB VDP_PALETTE_WHITE
