.equ HEADER_REGION	$4	; Export
.equ HEADER_ROM_SIZE	$c	; 32 kiB

.equ HEADER_PRODUCT_CODE	$04007

.IFDEF _J
	.equ HEADER_CHECKSUM	$6fa6
	.equ HEADER_REVISION	0
.ENDIF
.IFDEF _UE
	.equ HEADER_CHECKSUM	$88d4
	.equ HEADER_REVISION	1
.ENDIF
